[theme]
inherit = "basic"
stylesheets = []
sidebars = [
    "searchbox.html",
    "localtoc.html",
    "relations.html",
    "sourcelink.html",
]
pygments_style = { default = "monokai", dark = "monokai" }

# layout.htmlなどから呼び出す場合は`theme_<variable>`とする
[options]
variable = "default value"
right_sidebars = ["localtoc.html"]