[theme]
inherit = "basic"
stylesheets = []
sidebars = [
    "localtoc.html",
    "relations.html",
    "sourcelink.html",
    "searchbox.html",
]
pygments_style = { default = "monokai", dark = "monokai" }

[options]
variable = "default value"
